---
application:
  name: "roman-numeral-api-service"
  project: "roman-numeral-api"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "romnumdb"
  version: "8.0"
- type: "REDIS"
  name: "romnumrd"
  version: "5"
routers:
- name: "main-roman-numeral-api-service"
  routes:
  - application_name: "roman-numeral-api-service"
    paths:
    - "/*"
