# This stage installs our modules
FROM mhart/alpine-node:14

ARG QOVERY_ROUTER_MAIN_ROMAN_NUMERAL_API_SERVICE_URL="http://localhost"
ENV BASE_URL=$QOVERY_ROUTER_MAIN_ROMAN_NUMERAL_API_SERVICE_URL
RUN echo "BASE_URL set to $QOVERY_ROUTER_MAIN_ROMAN_NUMERAL_API_SERVICE_URL"

ENV PORT=3000
RUN echo "PORT set to $PORT"

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
RUN echo "NODE_ENV set to $NODE_ENV"

ARG API_PREFIX=''
ENV API_PREFIX=$API_PREFIX
RUN echo "API_PREFIX set to $API_PREFIX"

WORKDIR /app
COPY . .
RUN yarn install --production=false
RUN yarn build

EXPOSE 3000

ENTRYPOINT ["yarn", "start"]
