# This stage installs our modules
FROM mhart/alpine-node:14

ARG QOVERY_ROUTER_MAIN_ROMAN_NUMERAL_API_SERVICE_URL="http://localhost"
ENV BASE_URL=$QOVERY_ROUTER_MAIN_ROMAN_NUMERAL_API_SERVICE_URL
RUN echo "BASE_URL set to $QOVERY_ROUTER_MAIN_ROMAN_NUMERAL_API_SERVICE_URL"

ENV PORT=3000
RUN echo "PORT set to $PORT"

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
RUN echo "NODE_ENV set to $NODE_ENV"

ARG REDIS_URL='redis://redis'
ENV REDIS_URL=$REDIS_URL
RUN echo "REDIS_URL set to $REDIS_URL"

ARG DATABASE_URL='mysql://mysql'
ENV DATABASE_URL=$DATABASE_URL
RUN echo "DATABASE_URL set to $DATABASE_URL"

WORKDIR /app
COPY . .
RUN yarn install --production=false
RUN yarn build

EXPOSE 3000

ENTRYPOINT ["yarn", "start"]
