version: '2'
services:
  node:
    container_name: ${APP_PREFIX}-node
    image: mhart/alpine-node:14
    command: yarn dev
    environment:
      - PORT=3000
      - BASE_URL=http://localhost
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - ../:/app:delegated
    ports:
      - ${NODE_PORT}:3000

  mysql:
    container_name: ${APP_PREFIX}-mariadb
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_CRED}
      - MYSQL_USER=${DOCKER_CRED}
      - MYSQL_PASSWORD=${DOCKER_CRED}
      - MYSQL_DATABASE=${DOCKER_CRED}
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    container_name: ${APP_PREFIX}-redis
    image: redis:alpine
    command: redis-server --requirepass ${DOCKER_CRED}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/var/lib/redis:delegated
